### ISSUE TITLE
Linux: Core dump after changing from OpenGL to GTK

### ISSUE THREAD

**Issue by revvv** [revvv/gdash-export-CrLi#65]
1. Start GDash, open settings, select OpenGL, quit
2. - Start GDash, open settings, select GTK, crash __or__
    - Start GDash, open editor, crash

This happens already with my first Linux build!! Obviously I always switched between GTK and OpenGL, but did not quit GDash.

To workaround: Delete `gdash.ini` or edit it and set `graphics_engine=0` or `gdash --default-settings`

**Comment by revvv** [comment]
```
$ valgrind --track-origins=yes ./gdash -v
==3635== Use of uninitialised value of size 8
==3635==    at 0x5D4AF74: pthread_mutex_lock@@GLIBC_2.2.5 (pthread_mutex_lock.c:80)
==3635==    by 0x5F3756E: XrmQGetResource (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x5F18D49: XGetDefault (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x52A5F3A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52A8C53: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x527C8A8: cairo_surface_get_font_options (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52317F1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52356F1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x528C3AA: cairo_show_glyphs (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x5EECE12: ??? (in /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.5000.6)
==3635==    by 0x5EED094: ??? (in /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.5000.6)
==3635==    by 0x51CD5A2: pango_renderer_draw_glyph_item (in /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.5000.6)
==3635==  Uninitialised value was created by a heap allocation
==3635==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3635==    by 0x5F3B9AB: ??? (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x5F3BD22: XrmGetStringDatabase (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x5F18B2C: ??? (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x5F18D85: XGetDefault (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x635CA12: _XcursorGetDisplayInfo (in /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2)
==3635==    by 0x635DB0C: XcursorGetTheme (in /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2)
==3635==    by 0x50F73D0: gdk_x11_display_set_cursor_theme (in /usr/lib/x86_64-linux-gnu/libgdk-3.so.0.2404.29)
==3635==    by 0x4B4F670: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.29)
==3635==    by 0x4B5522F: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.29)
==3635==    by 0x4ADEA37: ??? (in /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.2404.29)
==3635==    by 0x554B744: g_cclosure_marshal_VOID__OBJECTv (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4)
==3635== 
==3635== Invalid read of size 4
==3635==    at 0x5D4AF74: pthread_mutex_lock@@GLIBC_2.2.5 (pthread_mutex_lock.c:80)
==3635==    by 0x5F3756E: XrmQGetResource (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x5F18D49: XGetDefault (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x52A5F3A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52A8C53: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x527C8A8: cairo_surface_get_font_options (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52317F1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52356F1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x528C3AA: cairo_show_glyphs (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x5EECE12: ??? (in /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.5000.6)
==3635==    by 0x5EED094: ??? (in /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.5000.6)
==3635==    by 0x51CD5A2: pango_renderer_draw_glyph_item (in /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.5000.6)
==3635==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==3635== 
==3635== 
==3635== Process terminating with default action of signal 11 (SIGSEGV)
==3635==  Access not within mapped region at address 0x10
==3635==    at 0x5D4AF74: pthread_mutex_lock@@GLIBC_2.2.5 (pthread_mutex_lock.c:80)
==3635==    by 0x5F3756E: XrmQGetResource (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x5F18D49: XGetDefault (in /usr/lib/x86_64-linux-gnu/libX11.so.6.4.0)
==3635==    by 0x52A5F3A: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52A8C53: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x527C8A8: cairo_surface_get_font_options (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52317F1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x52356F1: ??? (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x528C3AA: cairo_show_glyphs (in /usr/lib/x86_64-linux-gnu/libcairo.so.2.11600.0)
==3635==    by 0x5EECE12: ??? (in /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.5000.6)
==3635==    by 0x5EED094: ??? (in /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.5000.6)
==3635==    by 0x51CD5A2: pango_renderer_draw_glyph_item (in /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.5000.6)
==3635==  If you believe this happened as a result of a stack
==3635==  overflow in your program's main thread (unlikely but
==3635==  possible), you can try to increase the size of the
==3635==  main thread stack using the --main-stacksize= flag.
==3635==  The main thread stack size used in this run was 8388608.
==3635== 
==3635== HEAP SUMMARY:
==3635==     in use at exit: 87,708,937 bytes in 39,685 blocks
==3635==   total heap usage: 500,392 allocs, 460,707 frees, 260,787,790 bytes allocated
==3635== 
==3635== LEAK SUMMARY:
==3635==    definitely lost: 2,151 bytes in 8 blocks
==3635==    indirectly lost: 7,832 bytes in 328 blocks
==3635==      possibly lost: 131,187 bytes in 968 blocks
==3635==    still reachable: 87,343,095 bytes in 36,729 blocks
==3635==         suppressed: 0 bytes in 0 blocks
==3635== Rerun with --leak-check=full to see details of leaked memory
==3635== 
==3635== For lists of detected and suppressed errors, rerun with: -s
==3635== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped) 
```

**Comment by revvv** [comment]
```
$ gdb
Thread 1 "gdash" received signal SIGSEGV, Segmentation fault.
___pthread_mutex_lock (mutex=0x0) at ./nptl/pthread_mutex_lock.c:80
80	./nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  ___pthread_mutex_lock (mutex=0x0) at ./nptl/pthread_mutex_lock.c:80
#1  0x00007ffff682750f in XrmQGetResource () at /lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff6808d4a in XGetDefault () at /lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff7589f3b in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#4  0x00007ffff758cc54 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#5  0x00007ffff75608a9 in cairo_surface_get_font_options () at /lib/x86_64-linux-gnu/libcairo.so.2
#6  0x00007ffff75157f2 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#7  0x00007ffff75196f2 in  () at /lib/x86_64-linux-gnu/libcairo.so.2
#8  0x00007ffff75703ab in cairo_show_glyphs () at /lib/x86_64-linux-gnu/libcairo.so.2
#9  0x00007ffff692ee13 in  () at /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
#10 0x00007ffff692f095 in  () at /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
#11 0x00007ffff76405a3 in pango_renderer_draw_glyph_item () at /lib/x86_64-linux-gnu/libpango-1.0.so.0
#12 0x00007ffff7648df7 in pango_renderer_draw_layout_line () at /lib/x86_64-linux-gnu/libpango-1.0.so.0
#13 0x00007ffff7649405 in pango_renderer_draw_layout () at /lib/x86_64-linux-gnu/libpango-1.0.so.0
#14 0x00007ffff692fbf2 in pango_cairo_show_layout () at /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0
#15 0x00007ffff7a492e0 in gtk_render_layout () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff79b8b80 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff78f72e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff790b852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff79b23f5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff78947a3 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff7b1eb64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff78ff825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff78ff92d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff79dafc8 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff78f72e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff790b852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff79d82f5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff7b1eb64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff78ff825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff78ff92d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff79d7f91 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff78f72e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff790b852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff79d82d5 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff7b1eb64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#36 0x00007ffff78ff825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff78ff92d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff78a1571 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff78f72e1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff790b852 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff78a1e15 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff7b1eb64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007ffff78ff825 in gtk_container_propagate_draw () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007ffff78ff92d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007ffff7b3f60e in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#46 0x00007ffff7b1eb64 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff7b2adb1 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff79d154b in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#49 0x00007ffff76b1743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#50 0x00007ffff76c4151 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#51 0x00007ffff76c9221 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#52 0x00007ffff76c9418 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#53 0x00007ffff72b0700 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007ffff72b0863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x00007ffff76bec6f in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#56 0x00007ffff76ab2ad in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#57 0x00007ffff719a2c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#58 0x00007ffff7199c44 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#59 0x00007ffff71ee6c8 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#60 0x00007ffff71992b3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#61 0x00007ffff79c7cfd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#62 0x000055555569856b in gd_main_window_gtk_run(CaveSet*, NextAction&)
    (caveset=<optimized out>, na=@0x7fffffff7cb0: StartTitle) at gtk/gtkmainwindow.cpp:696
#63 0x0000555555665b41 in main_window_run_title_screen(CaveSet*, NextAction&)
    (caveset=<optimized out>, na=<optimized out>) at mainwindow.cpp:56
#64 0x000055555559de2b in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at main.cpp:337
 ```

**Comment by revvv** [comment]
I updated my Linux Mint which did not help and also tested with a Live Linux.

It looks like it's a GTK bug, but why the hell is it possible to switch from GTK to OpenGL and **NOT** vice versa??
